### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by wanchoi211** [duckdb/duckdb-wasm#1205]
### What happens?

the query gives back `memory access out of bounds`.

### To Reproduce

<img width="565" alt="Screen Shot 2022-11-30 at 10 52 15 AM" src="https://user-images.githubusercontent.com/6692076/204883889-659bf6eb-a58d-47cf-bbc9-00dfa432088a.png">

### OS:

x86_64

### DuckDB Version:

@duckdb/duckdb-wasm@1.19.1-dev2.0

### DuckDB Client:

Browser

### Full Name:

Alex Choi

### Affiliation:

Ladder insurance

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
Hi @wanchoi211!

Thanks for pointing out this problem, I don't have a solution (yet?!?), but I confirm there is something wrong going on here.
On the current live version it seems that either a wrong result is returned:
```
duckdb> create table t (a integer[], b integer[]);
┌┐
└┘
Elapsed: 3 ms

duckdb> insert into t values ([1,2,3], [4,5]);
┌───────┐
│ Count │
╞═══════╡
│     1 │
└───────┘
Elapsed: 5 ms

duckdb> insert into t values ([4,5], []);
┌───────┐
│ Count │
╞═══════╡
│     1 │
└───────┘
Elapsed: 2 ms

duckdb> select * from t, (select unnest(b) from t);
┌───────────┬────────┬───────────┐
│ a         ┆ b      ┆ unnest(b) │
╞═══════════╪════════╪═══════════╡
│ [1, 2, 3] ┆ [4, 5] ┆         4 │
│ [4, 5]    ┆ []     ┆         4 │
│ [0, 1, 1] ┆ [0, 0] ┆         5 │
│ [0, 2]    ┆ []     ┆         5 │
└───────────┴────────┴───────────┘
Elapsed: 3 ms
```
Or the `memory access out of bounds` is triggered, and it seems to be non-deterministic.

I will look into this, that is a ducdkb-wasm specific (potentially due to 32bit pointers, unsure) issue, thanks for the bug report.

**Comment by carlopi** [comment]
This has since been fixed.

Error "memory access out of bounds" was related to stack overflow, and most likely also the faulty version was a similar memory corruption.
