### ISSUE TITLE
"Package size exceeded the configured limit of 150 MB" for dev269/dev271 builds

### ISSUE THREAD

**Issue by holdenmatt** [duckdb/duckdb-wasm#1838]
### What happens?

(Apologies if you're already aware of this)

I was testing the latest dev build, and it looks like #1561 has come back since dev269.

### To Reproduce

These links don't work:
https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.1-dev269.0/dist/duckdb-browser-eh.worker.js
https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.1-dev271.0/dist/duckdb-browser-eh.worker.js

The last working version:
https://cdn.jsdelivr.net/npm/@duckdb/duckdb-wasm@1.28.1-dev258.0/dist/duckdb-browser-eh.worker.js

### Browser/Environment:

n/a

### Device:

n/a

### DuckDB-Wasm Version:

1.28.1-dev269.0

### DuckDB-Wasm Deployment:

n/a

### Full Name:

Matt Holden

### Affiliation:

Independent developer (Capset Labs)

**Comment by carlopi** [comment]
Thanks, I am looking at a fix!

**Comment by tobilg** [comment]
The lastest few dev version are now at 135mb again...

**Comment by carlopi** [comment]
This has since been fixed, by reviewing compilation flags to actually exclude more unnecessary code (https://github.com/duckdb/duckdb-wasm/pull/1860) and cherry-picking some work from the SMALLER_BINARY duckdb feature (https://github.com/duckdb/duckdb-wasm/pull/1864).

After that check on total size has been reinstated (https://github.com/duckdb/duckdb-wasm/pull/1865), so we should keep track of this going forward.
