### ISSUE TITLE
[Question] Wondering about serial HTTP range requests

### ISSUE THREAD

**Issue by pickledish** [duckdb/duckdb-wasm#381]
Hey guys, first just wanted to say, amazing work on this library, it's really impressive and I'm excited both to try things myself and to see what everyone else ends up doing with it 🙂

Anyways, this isn't an ISSUE so much as a QUESTION, something for my curiosity, so no worries if you don't get back to it for a while, or at all -- just figured I'd ask since I think it's interesting, hope that's ok.

So I wanted to play around a bit in the shell, and I uploaded a parquet file (a common one, a subset of the NYC taxi ride dataset, about 500MB in total) to a public S3 bucket and set the CORS so that it could be read by `shell.duckdb.org`. Then, I went to try out a few queries on the remote data file:

<img width="1006" alt="Screen Shot 2021-11-13 at 3 40 14 PM" src="https://user-images.githubusercontent.com/12091397/141658462-d4f6d336-1c53-42b0-94b3-511b68ecd94e.png">

First of all, I want to say again this is just amazing -- it pulled less then 30MB to answer an analytical query like this on a 500MB dataset, just blows my mind 💯 

But secondly -- it's kinda slow! That query took over a minute to come back, most of it seeming to be network. To confirm, I opened up the devtools and checked the network, and saw a whole bunch of tiny sequential range requests that seemed to be making sure we couldn't get too much work done at once:

<img width="1043" alt="Screen Shot 2021-11-13 at 3 43 09 PM" src="https://user-images.githubusercontent.com/12091397/141658543-7a6f4f49-f415-4e69-a2b9-cf29145f4b38.png">

So, I guess the TL;DR is that I want to know more about these! I'm guessing they can't "just" be fully parallelized, i.e. we need information from the last response in order to know what the next request looks like. But, maybe we could make fewer of these calls if we could increase the byte request size when the parquet is large? Or implement some kind of batching? Since this was the only hitch I ran into in an otherwise really cool experiment, I just wanted to hear your thoughts or plans.

Thanks a lot in advance, both for looking at my question and for building this in the first place!

**Comment by ankoh** [comment]
Hi @pickledish , thanks for the nice words.
Yes, we're facing a couple of problems here.

The most important one is, that we're (not yet) fully async during I/O. This has a few far reaching requirements for the query execution model that haven't been been tackled yet.
Right now, we're always sitting in a C++ callstack when doing I/O which restricts us to single blocking http reads (via XHR).
Threads would offer an escape hatch here but they're immediately bringing up the problems with cross-origin-isolation.
I'd love to implement the web filesystem using multiple concurrent fetches but that's not quite possible today.

So what we're doing right now is the following:
We're tracking 10 read heads per file and increase the read(ahead) size whenever we request sequential ranges.
But this leaves us with a few knobs that we have to tune ourselves, most importantly the readahead acceleration.
If you look at your screenshot, you can actually see that the requested byte ranges are growing roughly with a factor of 1.5. 

We could totally increase that to 2 or more to reduce the number of roundtrips.
The current factor of 1.5 was just a rough guess that may fall short with the network latencies.

https://github.com/duckdb/duckdb-wasm/blob/fc01f47603cdcc4dbd00d06d0c92c233d6b3ad3c/lib/src/io/web_filesystem.cc#L636-L644
https://github.com/duckdb/duckdb-wasm/blob/fc01f47603cdcc4dbd00d06d0c92c233d6b3ad3c/lib/include/duckdb/web/io/readahead_buffer.h#L127-L154
https://github.com/duckdb/duckdb-wasm/blob/fc01f47603cdcc4dbd00d06d0c92c233d6b3ad3c/lib/include/duckdb/web/io/readahead_buffer.h#L20-L24

**Comment by domoritz** [comment]
These knobs are indeed interesting. How did you come up with the 1KB start size? Given that each http request takes some time, maybe it's worth starting out larger than 1KB?

**Comment by ankoh** [comment]
This was just a blind first guess not backed by any data. We should totally accelerate faster.
Increasing the base size is a bit dangerous in case the user performs few small random accesses (this is not restricted to Parquet).
We have a page buffer sitting on top of the web filesystem which will buffer the file in 4KB pages anyway so the minimum range size for HTTP reads should be 4KB.

But increasing the sequential readahead acceleration makes a lot of sense the larger the latencies get.
So right now, we need 22 requests to max out at 16MB reads. If we go for a speedup of 8 instead of 1.5, we'll end up with only 5 roundtrips.

```
4096
6144
9216
13824
20736
31104
46656
69984
104976
157464
326196
354294
531441
797161
1195742
1793613
2690420
4035630
6053445
9080167
13620251
MAX 16 MB

4096
32768
262144
2097152
MAX 16 MB
```
Let me change that and we can try it out.
We could also make this user-configurable eventually.

**Comment by ankoh** [comment]
@pickledish Please try it out in the web shell with **@duckdb/duckdb-wasm@0.1.12-dev67.0**.

**Comment by ankoh** [comment]
In the ideal world, we'd want to push data into a DuckDB pipeline whenever one out of many fetch promises resolve. That would allow us to saturate the clients bandwidth very easily even with a single web worker. We'll get there eventually but there's some more invasive ground work to do in DuckDB.

@Mytherin recently migrated made the query execution push based which is already a fantastic step into that direction. The (only) big blocker that is left are the currently pull-based table functions. As soon as they are push-based, we can throw out all the blocking synchronous I/O calls and glue DuckDB to Js promises.

**Comment by bmschmidt** [comment]
First, let me echo @pickledish's praise and thanks.

I have a related question, I think. (Let me know if better placed elsewhere.)

I'm registering a remote parquet file which has one column (words) in sorted order to facilitate partial reads from the parquet metadata. 

```
await f.registerFileURL("words.parquet", "https://$sitename.benschmidt.org/$fname.parquet");
```

I then query it with 

```
f.query(`SELECT * FROM "words.parquet" WHERE word0 = '${r}'`))
```

It returns the results without pulling the whole file! Hooray!

But: if I run subsequent queries for the same word, I get a large number of serial HTTP range requests each time, rather than re-using the data I just loaded. They're served from the browser cache, so it at least doesn't require a full HTTP round trip; but my impression from the blog post was that it would use a buffered or web filesystem rather than the browser to generate the chunks. Is there some way to re-use the content inside duckdb?

(FWIW: this is one-grams from google ngrams, also including count metadata for words starting with 'A', 'B', and 'C' (capital only). '$fname' above is actually called 'word_small_page', and $sitename is 'ngrams'--but it's a biggish (150MB) file that I don't want getting autoscraped from this comment.)

**Comment by ankoh** [comment]
Hm, I think this points to a bug. Conceptually they should.
We deliberately pin files on URL registration so that they are not flushed out.
But you are right, it looks like we're currently evicting buffered pages a bit too eagerly when the file is closed.
Let me move this into a new issue, we need a few tests for pinned reopened files.

**Comment by ankoh** [comment]
@bmschmidt should be fixed, you can try it out it in the shell and in **0.1.12-dev72.0**.

**Comment by bmschmidt** [comment]
Tried this fix out, looks great. Thanks!

**Comment by ankoh** [comment]
Fixing this for now with the readahead acceleration and the caching bug fix for Benjamin. We can track the user-configurable readahead acceleration in a dedicated issue.
