### ISSUE TITLE
Timestamp fields returned as JavaScript Dates?

### ISSUE THREAD

**Issue by enjalot** [duckdb/duckdb-wasm#393]
It would be great if the client could convert timestamp fields to native JavaScript Date objects instead of the millisecond value.

Here is an example using both a parquet file and a csv file articulating the ask:
https://observablehq.com/@observablehq/duckdb-date-types

**Comment by enjalot** [comment]
It looks like Timestamp fields in the SQL database are returned as Timestamp fields in Arrow. There is a Date field in Arrow that does return native JavaScript dates. I haven't been able to figure out how to cast from Timestamp to Date, but it seems like it would make sense to be able to do that?

**Comment by ankoh** [comment]
Yes, DuckDB emits Arrow Timestamps in these cases. It is the more general type that can be specified with multiple units and an optional timezone.
DuckDB does not have support for time zones but this is [being worked on](https://github.com/duckdb/duckdb/issues/561).

Arrow does have the type Date64 which sits in a weird spot as it is defined as ms since epoch.
So Date64 seems to be a timestamp with millisecond resolution and no attached time zone? If that's the case we could introduce a flag in DuckDB-Wasm to autocast these timestamps to Date64.

Coming back to js-dates: I assume Arrow cannot emit plain js dates for timestamps by default since the Arrow timestamp type is too flexible. If, however, arrow-js maps Date64 to DateVectors by default, we can maybe live with such an autocast.

**Comment by domoritz** [comment]
Arrow has multiple date types so one of them may be the right fit. The date types are built from and return JS `Date` instances. The timestamp types are built and return numbers/bigints.

**Comment by ankoh** [comment]
Arrow does not have a plain Date type. Only in Js.
They have a 32 bit date32 that encodes days and a 64 bit date64 that encodes milliseconds since Unix epoch.
https://arrow.apache.org/docs/python/api/datatypes.html
The key question is whether it's semantically sound to autocast timestamp(ms) to date64 or whether this will turn into a footgun later.

**Comment by enjalot** [comment]
Is there someway I could prepare some tests or examples?
I was thinking of creating a parquet file using python to create columns for all the various date/time types with a few consistent dates. then could look at the resulting JS arrow and native JS interpretations?

**Comment by ankoh** [comment]
We could test this fairly easily without adding a parquet file right? I think there's some value in heaving self-contained jasmine tests if that's possible.
So in DuckDB-Wasm we have a fair amount of C++ tests and a(/too) few Typescript tests.
I started added regression tests for the GitHub issues [here](https://github.com/duckdb/duckdb-wasm/blob/master/packages/duckdb-wasm/test/regression/github_334.test.ts#L9).
Feel free to add a failing one there.
I'll probably have time for it at the weekend.

**Comment by enjalot** [comment]
anything I can do to help push this forward?
being able to use native dates (when importing from CSV) is the final hurdle for us being able to use this in a lot of places!

**Comment by ankoh** [comment]
@enjalot I added preliminary support for date autocasts in **1.11.1-dev53.0**.

You can now pass the option **castTimestampToDate**

https://github.com/duckdb/duckdb-wasm/blob/fc162831a524eabe1a7fbec80df3f33d8ba01276/packages/duckdb-wasm/src/bindings/config.ts#L1-L37

to the database config in open:
https://github.com/duckdb/duckdb-wasm/blob/fc162831a524eabe1a7fbec80df3f33d8ba01276/packages/duckdb-wasm/src/parallel/async_bindings.ts#L312-L315

Your adjusted test:
https://github.com/duckdb/duckdb-wasm/blob/fc162831a524eabe1a7fbec80df3f33d8ba01276/packages/duckdb-wasm/test/regression/github_393.test.ts#L5-L45

We can add per-query options later.
Let me know if it doesn't work for you.

**Comment by enjalot** [comment]
this is amazing, thank you so much!

**Comment by domoritz** [comment]
Should we set this as the default in the Observable client?

**Comment by ankoh** [comment]
We could do that by default in Observable, yes.
We need to revisit this when DuckDB get support for time zones though since we're blindly reinterpreting timestamps as (UTC) dates with this option.
Doing this by default might lead to unexpected query results.

**Comment by domoritz** [comment]
The [Observable DuckDB client](https://observablehq.com/@cmudig/duckdb) defaults to dates now.
