### ISSUE TITLE
Suggested way to handle read-only concurrency

### ISSUE THREAD

**Issue by david542542** [duckdb/duckdb-wasm#394]
In the use case that I have a query that I saved as a materialized view -- or let's just say a table called `SavedQuery`. Let's say I want to grab some statistics for each column, and there are ten columns. So the queries that I run are:

```
SELECT <info> FROM SavedQuery GROUP BY <field1>
SELECT <info> FROM SavedQuery GROUP BY <field2>
...
```

In the case that I run all ten queries in parallel (or whatever batch size I decide to use), what is the suggested way to run these queries concurrently?

**Comment by domoritz** [comment]
Is this a question for DuckDB or DuckDB wasm? If the latter, you can submit queries with independent connections but keep in mind that the memory usage will increase as the query results have to be kept in memory.

**Comment by ankoh** [comment]
Also note that your example is the perfect example for grouping sets and can be done in a single query.
```
SELECT <info> FROM SavedQuery GROUP BY GROUPING SETS ((<field1>), (<field2>)) 
```

Right now, DuckDB runs single-threaded in the web worker which means that concurrency right now can only really reduce the overhead of the message passing to and from the worker.
E.g. if you would do:
```
inflight.push(conn1.query('foo'));
inflight.push(conn2.query('bar'));
await Promise.all(inflight);
```
it would still execute `foo` and `bar` in sequence at the moment just because we're running with 1 thread without SharedArrayBuffers. That would also profit from a fully async DuckDB plan driver but we don't have that one yet.
It would, however, get rid of these additional event loop ticks that await for the response of `foo` before sending the next query.

Right now, it would even work to fire the queries over a single connection:
```
inflight.push(conn1.query('foo'));
inflight.push(conn1.query('bar'));
await Promise.all(inflight);
```
But this may break in the future. For example, using `send` instead of `query` here would be malformed since the connection is used to hold the query results (and stream them back to the main thread in a streaming fashion.

**Comment by luckyfanghe** [comment]
In background process, a query is running like CREATE TABLE IF NOT EXISTS tablename AS (SELECT * FROM "sample.csv");
the sample.csv has 10m csv file.
When run another query with independent connection like select 1, it takes 10s
i think the connections is not independent. What is the solution?

**Comment by ankoh** [comment]
Yes, DuckDB-Wasm can only execute one query at a time right now. We're looking into single-threaded concurrency in the web worker but this is not possible today.

**Comment by david542542** [comment]
@ankoh I see. Yea, [`GROUPING SETS`](https://duckdb.org/docs/sql/query_syntax/grouping_sets) is great in that particular use case. I suppose another one might be a dashboard where there are five different graphs/panels/etc and the queries would be better rendered in parallel (or 'batches' might be a better word if we want to limit the concurrency level).

As far as executing some single-threaded concurrency, is that something that occurs mostly on the DuckDB-wasm side or would need modifications in DuckDB itself? Is it a particularly complex item to implement? I wonder what the throughput of copying the Arrow buffer from one worker to another would be (If I recall correctly, I remember it taking a not-insignificant time to copy over the data when last testing something similar).

**Comment by david542542** [comment]
@domoritz 

> Is this a question for DuckDB or DuckDB wasm? If the latter, you can submit queries with independent connections but keep in mind that the memory usage will increase as the query results have to be kept in memory.

I meant specifically for the DuckDB-Wasm use case.

**Comment by ankoh** [comment]
> @domoritz
> 
> > Is this a question for DuckDB or DuckDB wasm? If the latter, you can submit queries with independent connections but keep in mind that the memory usage will increase as the query results have to be kept in memory.
> 
> I meant specifically for the DuckDB-Wasm use case. Just to clarify, do all connections occur within the same web-worker as long as they're tied to the same `duckdb.AsyncDuckDB` instance?

Yes they do

**Comment by ankoh** [comment]
> @domoritz
> 
> > Is this a question for DuckDB or DuckDB wasm? If the latter, you can submit queries with independent connections but keep in mind that the memory usage will increase as the query results have to be kept in memory.
> 
> I meant specifically for the DuckDB-Wasm use case. Just to clarify, do all connections occur within the same web-worker as long as they're tied to the same `duckdb.AsyncDuckDB` instance?

It's mostly on the DuckDB side. In DuckDB, you currently start a query and wait for it blockingly to finish. Consequently, if you have only the single thread of the Web worker, you're limited to executing 1 query at a time in your instance, independent of the connections. We're currently working on lifting this since this is tightly coupled with the asynchronous I/O story but that's the state of today.

**Comment by ankoh** [comment]
> I wonder what the throughput of copying the Arrow buffer from one worker to another would be (If I recall correctly, I remember it taking a not-insignificant time to copy over the data when last testing something similar).

The cost for copying is not zero but also not too severe.
The **packing** of the arrow buffer and reading everything again will hurt more than passing it to the worker.
Especially since you can pass the underlying ArrayBuffer as *Transferable* to postMessage.

**Comment by ankoh** [comment]
> @ankoh I see. Yea, [`GROUPING SETS`](https://duckdb.org/docs/sql/query_syntax/grouping_sets) is great in that particular use case. I suppose another one might be a dashboard where there are five different graphs/panels/etc and the queries would be better rendered in parallel (or 'batches' might be a better word if we want to limit the concurrency level).

Yes, this will come up when rendering 5 graphs in parallel. My advice here would be for now to just run the queries on different connections and await them independently. They will be executed one at a time but you don't need to serialize the `query` calls. Eventually, we'll be able to execute multiple queries concurrently on a single thread which will just speedup your execution without further adjustments on your end.

**Comment by ankoh** [comment]
Closing this for now. Feel free to open a follow up discussion.
