### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by applecool** [duckdb/duckdb-wasm#397]
Hey,

I am curious why the license has been changed from MIT to MPL? Is it something Duckdb is also going to do moving forward?

**Comment by applecool** [comment]
@ankoh

**Comment by ankoh** [comment]
The WebAssembly library grew out of a project that is independent from the CWI and the decision to license it under MPL-2.0 was my own.

**Comment by domoritz** [comment]
And many of the extensions such as the js node bindings are also user the MPL license: https://github.com/duckdb/duckdb/tree/master/tools/nodejs.

**Comment by ankoh** [comment]
But I'm open to discuss this. I deliberately chose MPL-2.0 over MIT since WebAssembly is still a very young target for databases and everyone should profit from upstream development in DuckDB-Wasm. MPL-2.0 should still be relaxed enough to facilitate the integration in an any kind of closed source project.

**Comment by applecool** [comment]
Thank you 😊
