### ISSUE TITLE
Publish react-duckdb to NPM

### ISSUE THREAD

**Issue by lexanth** [duckdb/duckdb-wasm#638]
I'm looking at using duckdb in a react app, so the code in react-duckdb is really useful.

Is there a plan to get it published to NPM? The code as-is would be a handy initial version.

**Comment by lexanth** [comment]
I've currently got the `react-duckdb` source duplicated in my app. It doesn't seem to need any special bundling itself, but I did need some webpack config to load the bundles (but they get provided to the `DuckDBPlatform` provider anyway).

Currently just passing the source of `react-duckdb` through `tsc` would appear to be enough, without doing any special bundling.

**Comment by ankoh** [comment]
I published react-duckdb as source library here: https://www.npmjs.com/package/@duckdb/react-duckdb
We'll bundle this properly in April.

**Comment by myagues** [comment]
Hi @lexanth, which webpack config did you use to make it work, I am currently facing this issue:

>./node_modules/@duckdb/react-duckdb/src/connection_provider.tsx
>Module parse failed: Unexpected token (7:5)
>You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. >See https://webpack.js.org/concepts#loaders
>| import { ResolvableStatus } from './resolvable';
>| 
>\> type DialerFn = (id?: number) => void;
>| 
>| export const poolCtx = React.createContext<imm.Map<number, duckdb.AsyncDuckDBConnection>>(imm.Map());

@ankoh the examples folder is very helpful, maybe it could be possible to add a react example alongside the other cases.

**Comment by ankoh** [comment]
@myagues maybe the demo itself helps you?
It is a user of react-duckdb and is written with react.
https://github.com/duckdb/duckdb-wasm/tree/master/packages/duckdb-wasm-app

react-duckdb is currently just a source-only library that is not transpiled.
So in order to use it, you'll have to include a typescript loader in your webpack config.
The demo just uses the ts-loader:
https://github.com/duckdb/duckdb-wasm/blob/65a7c808471987bb2eaaed106643e501f8b069ce/packages/duckdb-wasm-app/webpack.common.js#L36
