### ISSUE TITLE
Big file limitation

### ISSUE THREAD

**Issue by spff** [duckdb/duckdb-wasm#706]
Hi, I'm wondering if there is any limitation on browser/code or just my RAM is running out?  
I encountered `Uncaught (in promise) Error: malloc of size 1073741824 failed` when loading a 150MB parquet (6M cells).

**Comment by Alex-Monahan** [comment]
Hello!
Sorry that you ran into that issue! Could you please send us a few more details to help us troubleshoot? Could you provide your code, and ideally the parquet file? Also, what OS, browser, and DuckDB version are you using?

**Comment by spff** [comment]
chrome 100.0.4896.75 (Official Build) (arm64)
macOS Monterey 12.3.1 (21E258)
Chip:	Apple M1
Memory:	16 GB
@duckdb/duckdb-wasm 1.13.1-dev285.0

I can't provide the parquet but it has 200k rows, 6M cells, 150MB, and if I turn it into json, it'll be 450MB.  
Happened on `registerFileBuffer` and `registerFileURL` and `select * from "url.parquet"` as the example in doc

**Comment by ankoh** [comment]
`1073741824` are 1 GB. It depends a bit on your browser, but that might exceed your heap limit (of sometimes 2GB) quickly.
What kind of query are you executing?
Can you please try the following:

Open the web sell at shell.duckdb.org.
Add your parquet file with `.files add`.
Run a simple `select count(*) from 'filename'`.
That should work and will internally use the third option to register files `registerFileHandle` that will read the HTML 5 file handle directly instead of copying any content.

**Comment by spff** [comment]
It works for a 9XXMB parquet!
```
duckdb> select count(*) from 'bench.parquet';
┌──────────────┐
│ count_star() │
╞══════════════╡
│      1418442 │
└──────────────┘
Elapsed: 9 ms
```

I think it was the heap limit as you relied.
