### ISSUE TITLE
DuckDB in Pyodide?

### ISSUE THREAD

**Issue by aghasemi** [duckdb/duckdb-wasm#940]
Hi,

May I ask please, if there has been an attempt to use the DuckDB Python package in Pyodide? Given that the native code is already ported, there shouldn't a lot if work remaining. No?

Many thanks
Best

**Comment by ankoh** [comment]
Hey, there is quite a bit of work remaining depending on the feature set that you're asking for.
If you'd be searching for a bare-bone duckdb instance without http filesystem, the missing pieces would be mostly porting over the python api to pyodide.
But DuckDB-Wasm ships with a few more components to integrate with the browser apis.
(E.g. something like `SELECT * FROM 'http://foo'` uses a browser-specific web filesystem and runs in a web worker for synchronus XHRs)
This is significant effort to port since we'd have to interface with the DuckDB-Wasm API from pyodide.

**Comment by Alex-Monahan** [comment]
Hello! Have a look here! 
https://github.com/pyodide/pyodide/pull/2961

There was also some discussion about this in our Discord in the show and tell section!

**Comment by carlopi** [comment]
This can likely be closed, the path forward is compiling directly duckdb Python bindings within the Pyodide environment.

See https://github.com/duckdb/duckdb-pyodide.

Some lessons from duckdb-wasm are still relevant, mostly since it shaped the code to be compatible with the Web platform.

**Comment by carlopi** [comment]
Relevant: DuckDB is now one of the Pyodide official packages, https://github.com/pyodide/pyodide/pull/4684
